services:
  ollama:
    image: ollama/ollama:0.5.5
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
