services:
  archivist:
    build:
      context: .
      dockerfile: ../Dockerfile
      target: devcontainer
    volumes:
      - ..:/workspace:cached
      - shell_histories:/root/.cache/erlang-history
      - vscode_extensions:/root/.vscode-server-insiders
    command: sleep infinity
    network_mode: service:ollama

  ollama:
    image: ollama/ollama:0.5.7
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  shell_histories:
  ollama_data:
  vscode_extensions:
